spring.application.name=spring-webflux

logging.level.root=OFF
spring.main.banner-mode=off

spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/thesisdb}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:thesisuser}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:thesispass}

spring.r2dbc.pool.max-size=${POOL_SIZE:10}
spring.r2dbc.pool.initial-size=1
