spring.application.name=spring

logging.level.root=OFF
spring.main.banner-mode=off

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/thesisdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:thesisuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:thesispass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mvc.async.request-timeout=-1
